### Register a new user
POST http://localhost:3050/register
Content-Type: application/json

{
  "username": "testUser",
  "password": "testPassword",
  "ICnumber": "123456789012",
  "name": "Test User",
  "email": "testuser@example.com",
  "phonenumber": "987654321"
}

###Login with the registered user
POST http://localhost:3050/login
Content-Type: application/json

{
  "username": "safwannazarr",
  "password": "new_password_admin"
}

### Update user profile (replace <userToken> with the actual token obtained from the login response)
PATCH http://localhost:3050/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWF0IjoxNzA0NzEwNzk5LCJleHAiOjE3MDQ3MTQzOTl9.Xb75lxhST8srfI2IfP6J4LAAdnxPwTA8ugzLsy2JSEw

{
  "name": "Updated Test User",
  "email": "updateduser@example.com",
  "phonenumber": "1234567890",
  "password": "newPassword",
  "ICnumber": "9876543210"
}

### Create Appointment
POST http://localhost:3050/create-appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZndhbm5hemFyciIsImlhdCI6MTcwNDgyMjQyMywiZXhwIjoxNzA0ODI2MDIzfQ.XSKyWh-avSDguSWiuR-SKRvA67nykNi53G3Qp0KCnYA

{
  "name": "Appointment Name",
  "phonenumber": "+9876543210",
  "appointmentDate": "2024-01-15",
  "time": "10:00 AM",
  "purpose": "Regular checkup"
}

### View Appointment History
GET http://localhost:3050/appointment-history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWF0IjoxNzA0NzEwNzk5LCJleHAiOjE3MDQ3MTQzOTl9.Xb75lxhST8srfI2IfP6J4LAAdnxPwTA8ugzLsy2JSEw


### Delete Appointment by Date
DELETE http://localhost:3050/delete-appointment/2024-01-15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZndhbm5hemFyciIsImlhdCI6MTcwNDgyMjc2NiwiZXhwIjoxNzA0ODI2MzY2fQ.NHD2SKqwsFqnUtBSoTAR0-xjigz_YjoAXfsXxHPefnE


##### Admin Login - Get Admin Token
POST http://localhost:3050/admin-login
Content-Type: application/json

{
  "privateKey": "wanWAN1234!@#$"
}

##### Admin View All Data (User and Appointments)
GET http://localhost:3050/admin-view-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzA0NzEyNzU5LCJleHAiOjE3MDQ3MTYzNTl9.Qf_9t8r7m59wHAt-BTxvOETU7F2lXDy0sK2X-VnB1e4

##### Admin Edit User Data (Replace USERNAME with the actual username)
PATCH http://localhost:3050/admin-edit-user/safwannazarr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzA0ODE1NjY5LCJleHAiOjE3MDQ4MTkyNjl9.y4So_BEblZSdKNudUZig6jNGC0-Wu6JWW4bH6WoRYQQ
Content-Type: application/json

{
  "name": "John Doe Admin Updated",
  "email": "john.admin.updated@example.com",
  "phonenumber": "+1234567890",
  "password": "new_password_admin",
  "ICnumber": "123456789012"
}











