####### Register User 
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "safwan",
  "password": "safwan",
  "ICnumber": "9",
  "name": "wan",
  "email": "wan.com",
  "phonenumber": "9"
}

######## Login User
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "safwan",
  "password": "safwan"
}

######## Edit User Profile
PATCH http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZndhbiIsImlhdCI6MTcwMzY4MDc2MX0.EfNrIXWtazmISRZaUynwTgoAFc4X-GjeaS94b0t3c34

{
  "name": "amri ",
  "email": "updated@gmail.com",
  "phonenumber": "0194327870"
}


######## Create Appointment
POST http://localhost:3000/create-appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZndhbiIsImlhdCI6MTcwMzY4MDc2MX0.EfNrIXWtazmISRZaUynwTgoAFc4X-GjeaS94b0t3c34

{
  "name": " amri",
  "phoneNumber": "10",
  "appointmentDate": "31",
  "time": "10:00 AM",
  "purpose": "makn2"
}

######## View Appointment History
GET http://localhost:3000/appointment-history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZndhbiIsImlhdCI6MTcwMzY4MDc2MX0.EfNrIXWtazmISRZaUynwTgoAFc4X-GjeaS94b0t3c34

######## Admin Login
POST http://localhost:3000/admin-login
Content-Type: application/json

{
  "privateKey": "123"
}

######## Admin View All Data
GET http://localhost:3000/admin-view-data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzAzNjgwODE1fQ.RWCHoM76Sm9vEJsGkbJo7LdzFpkyPtoQ8FSWPJ8hl9E

######## Admin Update User Data
PUT http://localhost:3000/admin-update-user/testuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzAzNjgwODE1fQ.RWCHoM76Sm9vEJsGkbJo7LdzFpkyPtoQ8FSWPJ8hl9E

{
  "name": "Updated Admin User"
  
}
